############################
## CHANGE THESE
############################

baseURL: "https://shainamurphy.com"
title: Shaina Murphy

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
