############################
## Author
############################

author:
  name: Shaina Murphy
  image: headshot.png
  greeting: "Aspiring human computer interaction researcher. :tada:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/shainamurphy/
  # - link: https://github.com/shainamurphy/
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/shainamurphy/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:shainanmurphy@gmail.com
  # - discord: 
  - orcid: https://orcid.org/0009-0006-2683-3694
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Shaina Murphy
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
